apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: exam
  git:
    syncRepo: "https://github.com/nhsy/csp-config-management.git"
    syncBranch: "anthos-lab"
    syncWait: 5
    secretType: none
    policyDir: "foo-corp"

#  policyController:
#    enabled: true
#    # Uncomment to prevent the template library from being installed
#    # templateLibraryInstalled: false
#    # Uncomment to enable support for referential constraints
#    # referentialRulesEnabled: true
#    # Uncomment to disable audit, adjust value to set audit interval
#    # auditIntervalSeconds: 0
#    # Uncomment to log all denies and dryrun failures
#    # logDeniesEnabled: true
#    # Uncomment to exempt namespaces
#    # exemptableNamespaces: ["namespace-name"]

#  binauthz:
#    enabled: true
#    # Information needed to determine which policy to enforce
#    policyRef:
#      gkeCluster:
#        # The name (or ID) of the GCP project containing the cluster
#        project: qwiklabs-gcp-01-bb73283bd87f
#        # Location of this cluster
#        location: us-central1-b
#        # The name of the cluster.
#        name: exam